document_root = "/9845/";

document.write("    <a name='top' id='top'></a>");
document.write("    <div id='header' style='background:#DAC78D'>");
document.write("      <div style='width: 900px; padding: 0;'>");
document.write("        <a href='" + document_root + "index.html'><img src='" + document_root + "common/images/home.png' width='93' height='100' border='0' /></a><img src='" + document_root + "common/images/topbar_title.png' width='800' height='100' border='0' />");
document.write("      </div>");
document.write("    </div>");
document.write("    <!-- end #header -->");
document.write("");
document.write("    <div id='gradient1'></div>");
document.write("");
document.write("    <div style='margin-left: 0px; margin-right: 0px;'>");
document.write("      <ul id='MenuBar1' class='MenuBarHorizontal'>");
document.write("        <li>");
document.write("          <a class='MenuBarItemSubmenu' href='" + document_root + "'>Home</a>");
document.write("          <ul>");
document.write("            <li><a href='" + document_root + "home/about.html'>About This Site</a></li>");
document.write("            <li><a href='" + document_root + "home/news.html'>News</a></li>");
document.write("            <li><a href='/sphider/search.php'>Search</a></li>");
document.write("            <li><a href='" + document_root + "home/support.html'>Supporting This Site</a></li>");
document.write("            <li><a href='" + document_root + "home/guestbook.php'>Guestbook</a></li>");
document.write("            <li><a href='" + document_root + "home/contact.php'>Contact</a></li>");
document.write("            <li><a href='" + document_root + "home/sitemap.html'>Sitemap</a></li>");
document.write("            <li><a href='" + document_root + "home/downloads.html'>Downloads</a></li>");
//document.write("            <li><a href='" + document_root + "home/forum.html'>Forum</a></li>");
document.write("            <li><a href='" + document_root + "home/terms.html'>Terms of Use</a></li>");
document.write("          </ul>");
document.write("        </li>");
document.write("        <li>");
document.write("          <a class='MenuBarItemSubmenu' href='" + document_root + "history'>History</a>");
document.write("          <ul>");
document.write("            <li><a href='" + document_root + "history/workstation'>The Workstation Era</a></li>");
document.write("            <li><a href='" + document_root + "history/story'>The 9845 Story</a></li>");
document.write("            <li><a href='" + document_root + "history/products'>The Product Line</a></li>");
document.write("            <li><a href='" + document_root + "history/team'>The Production Team</a></li>");
document.write("            <li><a href='" + document_root + "history/comparison'>Comparing the 9845</a></li>");
document.write("          </ul>");
document.write("        </li>");
document.write("        <li>");
document.write("          <a class='MenuBarItemSubmenu' href='" + document_root + "hardware'>Hardware</a>");
document.write("          <ul>");
document.write("            <li><a href='" + document_root + "hardware/packages'>Packages &amp; Options</a></li>");
document.write("            <li><a href='" + document_root + "hardware/9845a'>The 9845A/S</a></li>");
document.write("            <li><a href='" + document_root + "hardware/9835'>The 9835A/B</a></li>");
document.write("            <li><a href='" + document_root + "hardware/9845b'>The 9845B/T</a></li>");
document.write("            <li><a href='" + document_root + "hardware/9845c'>The 9845C</a></li>");
document.write("            <li><a href='" + document_root + "hardware/architecture'>System Architecture</a></li>");
document.write("            <li><a href='" + document_root + "hardware/processors'>Processors</a></li>");
document.write("            <li><a href='" + document_root + "hardware/displays'>CRT Displays</a></li>");
document.write("            <li><a href='" + document_root + "hardware/assemblies'>Assemblies</a></li>");
document.write("            <li><a href='" + document_root + "hardware/interfaces'>Interfaces</a></li>");
document.write("            <li><a href='" + document_root + "hardware/peripherals'>Peripherals</a></li>");
document.write("          </ul>");
document.write("        </li>");
document.write("        <li>");
document.write("          <a class='MenuBarItemSubmenu' href='" + document_root + "software'>Software</a>");
document.write("          <ul>");
document.write("            <li><a href='" + document_root + "software/architecture'>Software Architecture</a></li>");
document.write("            <li><a href='" + document_root + "software/packages'>HP Software Packages</a></li>");
document.write("            <li><a href='" + document_root + "software/hpplus'>HP PLUS Software</a></li>");
document.write("            <li><a href='" + document_root + "software/exchange'>Exchange Library</a></li>");
document.write("            <li><a href='" + document_root + "software/sysutils'>System Utilities</a></li>");
document.write("            <li><a href='" + document_root + "software/os'>Operating System</a></li>");
document.write("            <li><a href='" + document_root + "software/basic'>9845 BASIC</a></li>");
document.write("            <li><a href='" + document_root + "software/optionroms'>Option ROMs</a></li>");
document.write("            <li><a href='" + document_root + "software/binaries'>Binary Programs</a></li>");
document.write("            <li><a href='" + document_root + "software/screenart'>Screen Art</a></li>");
document.write("            <li><a href='" + document_root + "software/games'>Games</a></li>");
document.write("          </ul>");
document.write("        </li>");
document.write("        <li>");
document.write("          <a class='MenuBarItemSubmenu' href='" + document_root + "documents'>Documents</a>");
document.write("          <ul>");
document.write("            <li><a href='" + document_root + "documents/software'>Software Documentation</a></li>");
document.write("            <li><a href='" + document_root + "documents/user'>User Documentation</a></li>");
document.write("            <li><a href='" + document_root + "documents/service'>Service Documentation</a></li>");
document.write("            <li><a href='" + document_root + "documents/peripherals'>Peripherals</a></li>");
document.write("            <li><a href='" + document_root + "documents/catalogs'>Catalogs &amp; Brochures</a></li>");
document.write("            <li><a href='" + document_root + "documents/misc'>Magazines, Patents & Schematics</a></li>");
document.write("          </ul>");
document.write("        </li>");
document.write("        <li>");
document.write("          <a class='MenuBarItemSubmenu' href='" + document_root + "projects'>Projects</a>");
document.write("          <ul>");
document.write("            <li><a href='" + document_root + "projects/romdump'>ROM Dumping Project</a></li>");
document.write("            <li><a href='" + document_root + "projects/romboard'>ROM Board</a></li>");
document.write("            <li><a href='" + document_root + "projects/hpdrive'>HPDrive</a></li>");
document.write("            <li><a href='" + document_root + "projects/hpdir'>HPDir</a></li>");
document.write("            <li><a href='" + document_root + "projects/hpprint'>HPPrint</a></li>");
document.write("            <li><a href='" + document_root + "projects/fdio'>Fdio</a></li>");
document.write("            <li><a href='" + document_root + "projects/9111'>Digitizer/Plotter/Sound</a></li>");
document.write("            <li><a href='" + document_root + "projects/utilities'>9845 Utilities</a></li>");
document.write("            <li><a href='" + document_root + "projects/assembler'>9845 Assembler</a></li>");
document.write("            <li><a href='" + document_root + "projects/mouse'>9845 Mouse</a></li>");
document.write("            <li><a href='" + document_root + "projects/featureboard'>Feature Board</a></li>");
document.write("            <li><a href='" + document_root + "projects/emulator'>HP 9845 Emulator</a></li>");
document.write("          </ul>");
document.write("        </li>");
document.write("        <li>");
document.write("          <a class='MenuBarItemSubmenu' href='" + document_root + "tutorials'>Tutorials</a>");
document.write("          <ul>");
document.write("            <li><a href='" + document_root + "tutorials/preparations'>Before First Turning On</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/troubleshooting'>Troubleshooting</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/savetapes'>Saving Tapes</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/romdump'>Dumping ROMs</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/pcconnect'>Connecting to the PC</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/tapedrives'>Tape Drive Repair</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/ramrepair'>RAM Repair</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/networks'>9845 Networks</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/bitmaps'>Using Bitmaps</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/gamedesign'>9845 Game Design</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/testrom'>9845 Test ROM</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/analyzer'>Using Logic Analyzers</a></li>");
document.write("            <li><a href='" + document_root + "tutorials/hpib'>HP-IB/GPIB</a></li>");
document.write("          </ul>");
document.write("        </li>");
document.write("        <li><a href='" + document_root + "links'>Links</a></li>");
document.write("      </ul>");
document.write("    </div>");
document.write("");
document.write("    <div id='gradient2'></div>");
document.write("    <!-- end navigation -->");
